### ISSUE TITLE
update dependencies and remove allow of RUSTSEC-2023-0024

### ISSUE THREAD

**Issue by jordanrfrazier** [kaskada-ai/kaskada#155]
branch is explicitly allowing above rustsec vulnerability, as our dependencies haven't updated yet. This is the original failing job. https://github.com/kaskada-ai/kaskada/actions/runs/4510764637/jobs/7942099545, with allow pr: https://github.com/kaskada-ai/kaskada/pull/153/files

**Comment by bjchambers** [comment]
I believe this was fixed by #179. Could you verify, and if so make sure not to check-in the the allowance?

**Comment by jordanrfrazier** [comment]
Removed explicit allows in commit 428ae2f18097b859955aa9b8e09f7c04e4fe6cc5
