### ISSUE TITLE
Facing problem with installation

### ISSUE THREAD

**Issue by therapon** [kaskada-ai/kaskada#201]
### Discussed in https://github.com/kaskada-ai/kaskada/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **srikannanb** March 31, 2023</sup>
Im not sure this is the right place to ask questions. I'm using mac and I'm following the steps mentioned on the home page to install the kaskada. I getting following message.

./kaskada-cli: line 1: Not: command not found. engine and  manager are working as expected

"https://github.com/kaskada-ai/kaskada/releases/download/engine%40v$VERSION/kaskada-cli-$OS-$ARCH" -o kaskada-cli"</div>

**Comment by Illumaria** [comment]
Hi @therapon!

I'm not a maintainer, but I faced the same problem on Linux, got interested in this, did some digging and probably found the reason.

Can you please provide the output of the following command?
```
uname -ms
```
You see, in the [instructions](https://kaskada.io/docs-site/kaskada/main/installing.html#using-kaskada-with-the-command-line-cli) for installing Kaskada via CLI these lines are present:
```
ARCH=$(uname -m | awk '{print tolower($0)}')
OS=$(uname -s | awk '{print tolower($0)}')
```
For me, the first one turns `ARCH` into `x86_64`:
![image](https://user-images.githubusercontent.com/47138294/229529520-f9e56fe4-5d21-4087-8aa8-14ce211f025f.png)
But if you look closely at the [list of available assets](https://github.com/kaskada-ai/kaskada/releases/tag/engine%40v0.4.1) for the version `0.4.1` (default one in the instruction), you can see two problems:
1. There are no assets for `kaskada-cli` at all.
2. There are no assets for the `x84_64` architecture. I mean, there is `amd64` which is literally the same, but `curl` command doesn't care about that.

Alright, so what can we do?
1. Switch `VERSION` to the [latest release](https://github.com/kaskada-ai/kaskada/releases), which is [0.5.4](https://github.com/kaskada-ai/kaskada/releases/tag/engine%40v0.5.4) at the moment. This version contains assets for `kaskada-cli`.
2. Manually set the correct `ARCH`. In my case, if I set it to `amd64`, everything works like a charm:
![image](https://user-images.githubusercontent.com/47138294/229531963-8529bd60-bf75-48ce-b1dc-86c43ab6b099.png)

**Comment by therapon** [comment]
HI @Illumaria 

> I'm not a maintainer, but I faced the same problem on Linux, got interested in this, did some digging and probably found the reason.

 Apologies for that, the instructions were incorrect for a couple of reasons as you point out below. We updated the instructions in a way that you do not need to set the version number, the command will grab the latest released version, and, works for Unix-like OSes including OSX. 


See https://kaskada.io/docs-site/kaskada/main/getting-started/hello-world-cli.html for updated command 
 
> Can you please provide the output of the following command?
> 
> ```
> uname -ms
> ```
> 
> You see, in the [instructions](https://kaskada.io/docs-site/kaskada/main/installing.html#using-kaskada-with-the-command-line-cli) for installing Kaskada via CLI these lines are present:
> 
> ```
> ARCH=$(uname -m | awk '{print tolower($0)}')
> OS=$(uname -s | awk '{print tolower($0)}')
> ```
> 
> For me, the first one turns `ARCH` into `x86_64`: ![image](https://user-images.githubusercontent.com/47138294/229529520-f9e56fe4-5d21-4087-8aa8-14ce211f025f.png) 

You are correct. On Linux machines `x86_64` is what is typically reported and is an alias for `amd64`. The new command includes the line `grep $(uname -m | sed 's/x86_64/amd64/') |\` to make that translation. 

> But if you look closely at the [list of available assets](https://github.com/kaskada-ai/kaskada/releases/tag/engine%40v0.4.1) for the version `0.4.1` (default one in the instruction), you can see two problems:
> 
>     1. There are no assets for `kaskada-cli` at all.

You are correct here again :). The binary for the CLI was not present in that release. It is present in later releases. 

> 
>     2. There are no assets for the `x84_64` architecture. I mean, there is `amd64` which is literally the same, but `curl` command doesn't care about that.
> 

Yes. This is relevant to your point about the return values of `uname -ms` above. 

> 
> Alright, so what can we do?
> 
>     1. Switch `VERSION` to the [latest release](https://github.com/kaskada-ai/kaskada/releases), which is [0.5.4](https://github.com/kaskada-ai/kaskada/releases/tag/engine%40v0.5.4) at the moment. This version contains assets for `kaskada-cli`.
> 
>     2. Manually set the correct `ARCH`. In my case, if I set it to `amd64`, everything works like a charm:
>        ![image](https://user-images.githubusercontent.com/47138294/229531963-8529bd60-bf75-48ce-b1dc-86c43ab6b099.png)

Correct again, you can solve the 2 issues that you identified by making these changes to the *old* instructions. That is very close to what I had to do to ensure that I could get the binaries and verify that I could overcome the errors you identified. 

After some digging on the GitHub response from their API I was able to come up with a more robust command to download the Kaskada binaries which lead to the new instructions on our page. 

See https://kaskada.io/docs-site/kaskada/main/getting-started/hello-world-cli.html for updated command 

We created this issue though because we would like to make it better by 
 having one instruction (hopefully a one liner) that will work for *all* OSes and Architectures.

**Comment by Illumaria** [comment]
> We created this issue though because we would like to make it better by having one instruction (hopefully a one liner) that will work for _all_ OSes and Architectures.

Whoops, I didn't notice you'd already figured it all out, sorry. 😅  In this case, I'll drop by if I have any further ideas on the topic.
