### ISSUE TITLE
bug: file:///

### ISSUE THREAD

**Issue by kevinjnguyen** [kaskada-ai/kaskada#239]
**Description**
There is currently discrepancy between the usage of the Python Client and the CLI. There is various support from the API to the CLI for the file paths allowed. In the Python Client, we are not able to pass in the file URI e.g. `file://awkward.tacos.parquet` since it creates the path under the hood.

**To Reproduce**
1. Load data to a table using the `file://path` instead of the path.
```python
kaskada.load("table_name", "file:///Users/kevin.nguyen/Desktop/super-secret.parquet")
```

**Actual Behavior**
Throws a validation error.

**Expected Behavior**
The paths provided should be the same across the Python Client and the CLI.

**Comment by bjchambers** [comment]
It's unclear from the description here what the bug is, or what the fix should be. Could you update things?
