### ISSUE TITLE
feat: Add search plugin to Antora and UI changes to show search bar

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#249]
**Summary**
Our docs should be searchable

**Comment by bjchambers** [comment]
It seems like the Lunr extension is the way to go: https://gitlab.com/antora/antora-lunr-extension

@therapon is this something you'd be able to look at setting up? If not, I may be able to take it.

**Comment by therapon** [comment]
I had that on my todo list--I did some reading and the easiest way to get search on the docs is Lunr. Let me give it a go and report back in a couple of days, it is mostly setting some time to do it at this point.

**Comment by therapon** [comment]
2 PRs to add search bar and they should be done and merged *in this order* 

1. https://github.com/kaskada-ai/docs-ui/pull/4
2. https://github.com/kaskada-ai/docs-site/pull/12

**Comment by therapon** [comment]
Code is live and search is working. 
Closing
