### ISSUE TITLE
feat: Default to storing data in `~/.cache/data`, rather than `data`

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#253]
**Summary**
The current data location is often user visible, and users interpret as part of the system's public API. We should move it to an internal location so it's clear that the contents aren't intended to be poked at.

**Comment by kevinjnguyen** [comment]
It looks like we set the object store path in the[ main.go line 59.](https://github.com/kaskada-ai/kaskada/blob/main/wren/main.go#L59) We can probably make this a Python client responsibility or change the default in Wren.

**Comment by kerinin** [comment]
Let's change the default - users can still use `./data` if they want, but I would prefer not to expose this directory by default.

**Comment by epinzur** [comment]
@kevinjnguyen I'm re-assigning this to you.
