### ISSUE TITLE
feat: Improve Python's subprocess management

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#254]
**Summary**
The way that the Python library manages the kaskada subprocesses could be improved in a couple ways:

* Raise an exception in Python if the subprocess can’t be started (ie if it can’t bind the port b/c another process is still running), * Raise an exception if the subprocess exits prematurely
* (maybe?) Create the subprocess on-demand if it has been terminated, for example by IPython

The last point comes out of some issues @stinkymatt was having where the process seems to be terminating for no reason.

**Comment by epinzur** [comment]
probably should move wren db storage to be local and not in-memory

**Comment by kevinjnguyen** [comment]
The latest PR #373 iterates on the next implementation of the Local Session to automatically recover from local session failure. Please take a look at this [example notebook](https://github.com/kaskada-ai/kaskada/blob/main/examples/Local%20Session%20(Next%20Iteration).ipynb) for a documented feature rundown.
