### ISSUE TITLE
bug: List table view in Jupyter doesn't show anything

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#258]
**Description**
When working through the user study in vanilla, local Jupyter, the list table response wasn't rendered.

**Comment by kevinjnguyen** [comment]
@kerinin can you verify this is still a problem? The latest release shows an empty rendering.

<img width="619" alt="Screenshot 2023-05-05 at 11 14 47 AM" src="https://user-images.githubusercontent.com/15032894/236511828-8abb0475-3f75-49ec-b2d5-94e5ccb127cc.png">

**Comment by kevinjnguyen** [comment]
This is no longer an issue in the latest version of the Kaskada client. Verified in the ecommerce jupyterhub example. Closing for now, if this is still an issue please re-open.
