### ISSUE TITLE
feat: Tabbed examples in the docs

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#260]
**Summary**
It would be nice to have something along the lines of https://github.com/asciidoctor/asciidoctor-tabs so that we could show different code samples in different contexts:
* For installing on different OS's we could have tabs for different install scripts
* For different clients we could have tabs for CLI/Python/Jupyter

**Comment by bjchambers** [comment]
I think having tabs would be good -- as you say, it could be useful for some things such as install scripts.

For using this with different clients, I'm 50/50 on this. It can be useful when there are different ways of expressing very similar concepts. For instance, the [Beam programming guide](https://beam.apache.org/documentation/programming-guide/#windowing) does this when introducing concepts like windowing. One nice thing is all the tabs on the page are "linked" so changing to Python in one example changes all of them. On the other hand, I think a lot of content is better when it focuses on a specific client. For instance, the concepts we need to explain for a Python example will be different from doing the same example in the CLI.

So -- probably good for us to develop, but may not be as useful for the different clients thing as we think.

**Comment by therapon** [comment]
So it seems like we can use this issue to first enable tabs in antora and then it is up to us to use them effectively. So let me take on the task to enable them first.
