### ISSUE TITLE
docs: Align naming/docs/errors around entity type

### ISSUE THREAD

**Issue by bjchambers** [kaskada-ai/kaskada#268]
**Description**
If we want to implicitly use multiple tables within the same expression they should have the same entity type.
If we don't specify the entity type, it defaults to the name of the table.
Thus, to use multiple tables implicitly, we need them to set their entiy type.

https://kaskada.io/docs-site/kaskada/main/developing/tables.html#creating-a-table

We do say:

> A name describing the type of entity, for example "User" or "Purchase".

But this doesn't tell me what the parameter to use to set that name is.

**Comment by kerinin** [comment]
This was recently changed, and now reads:

> The type of entity is specified using the grouping_id parameter. The grouping ID specifies what kind of entity each event is associated with, for example "User" or "Purchase". When combining events from different tables, events with the same entity key and grouping ID are treated as being part of the same entity.

I wouldn't consider this a bug though - if we want to associate "bugs" with docs it would probably be best to use that tag for docs that are wrong, rather than docs that are incomplete.

**Comment by bjchambers** [comment]
> We've discussed eliminating the group ID a couple times in the past - I think it might be worth revisiting that conversation. I really struggled trying to document that field, in terms of explaining the behavior and why you would want it to behave that way.

I think I'm generally in favor eliminating, assuming we do something else to address the fact that implicit joins are very easy to create odd behaviors with. For instance, even the `A | when(B) | when(C)` case we looked at recently has this problem.

I think some kind of explicit join to bring multiple tables into scope would probably be *better* at solving both the implicit join case, as well as the entity type case.
