### ISSUE TITLE
bug: update python client to not download latest

### ISSUE THREAD

**Issue by epinzur** [kaskada-ai/kaskada#308]
While we are releasing new versions of the manager & engine, the `latest` tag of the executables is not available.

In the future there will be updates to the services that are incompatible with versions of the python code.  The python system should have some included range of manager/engine versions that it knows it is compatible with and download the newest available version in that range.

**Comment by kevinjnguyen** [comment]
Thanks for filing this bug. First, please update the description of your error message to follow the [Bug Template](https://github.com/kaskada-ai/kaskada/issues/new?assignees=&labels=bug&template=bug_report.md&title=bug%3A+...). This will drastically reduce the overhead required to address the bug.

With regards to your suggestion for the Python system, I believe you are suggesting a windowed range of versions that the current Python version is compatible with. For example:
* Python Client Version 0.1.6 is only compatible with releases [0.6.1, 0.6.2]
* Python Client Version 0.2.0 is only compatible with releases [0.7.0+]

This would require each version of the Python client to lockdown the range of versions they are compatible with. We most likely can use the library [python-semanticversion](https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification) to help us parse out the semantic versions of the releases.

Do you have suggestions on the compatibility of the client to the engine/manager or are you implying that the versions are explicitly always stated?

**Comment by kevinjnguyen** [comment]
In a discussion, we discussed this is a problem for further out in the future. Once we have achieved version 1.0.0 then we should revisit this.
