### ISSUE TITLE
feat: Improve the error message when you try to query an empty table

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#326]
**Summary**
If you create a table, but don't load any data into and then try to query it, you get this error:

```
FTL error="rpc error: code = NotFound desc = data_token not found" 
```

...which isn't very actionable. It would be much better if it said something like "You have tried to query a table that doesn't contain any data - please load some data before querying" or something.

**Comment by epinzur** [comment]
This error only occurs on a fresh Kaskada system, where zero dataTokens have been created.
