### ISSUE TITLE
CLI load table command - fails to locate file in provided --file-path option

### ISSUE THREAD

**Issue by jeffbanks** [kaskada-ai/kaskada#327]
**Description**
When loading data using kaskada cli:

```
kaskada-cli load \
    --table Purchase \
    --file-path file:///path/to/file.parquet \
    --file-type parquet
```

**To Reproduce**

1. Ensure a file target is available (e.g. purchase.parque) @ `${PWD}`.
2. Issue the following command using cli load operation.

`kaskada-cli load --table Purchase --file-type parquet --file-path file:///${PWD}/purchase.parque`
 

**Actual Behavior**

The following error is returned:
```
10:27AM INF starting load
10:27AM FTL  error="at least one `file` flag must be set"
```

**Expected Behavior**

Loads the table with the parque file contents provided in purchase.parque.

**Additional context**
* Possible recent change located [here](https://github.com/kaskada-ai/kaskada/blob/2c84805c8de80d7dcada2145c84a3eb3a37820dd/clients/cli/cmd/load.go#L53) w/ StringSliceVar.
* Ubuntu 20.04.6 LTS

* Installed `cli`, `manager`, and `engine` using:
`https://api.github.com/repos/kaskada-ai/kaskada/releases/latest`

**Comment by kevinjnguyen** [comment]
@jeffbanks thanks for reporting this bug. I think this is a documentation issue and I've proposed the new doc changes in #335 . For now, can you try: 
```
./kaskada-cli table load \
     Purchase \
     file://${PWD}/purchase.parquet
```

**Comment by epinzur** [comment]
@jeffbanks Could also please try Kevin's suggestion with CLI version 0.6.2? https://github.com/kaskada-ai/kaskada/releases/tag/engine%40v0.6.2

There is a bunch of new functionality for the CLI in this release.

**Comment by jeffbanks** [comment]
Right on, doing the upgrade and using @kevinjnguyen suggestion did the trick.  Thank you for the quick turnaround!

```
== creating table
tableId: d77944ff-e594-4da9-b93b-8b3f4decf676
tableName: Purchase
timeColumnName: purchase_time
entityKeyColumnName: customer_id
createTime: 2023-05-09T19:54:07.757210Z
updateTime: 2023-05-09T19:54:07.757212Z

== listing table
Purchase

== Loading file into the purchase table
.../kaskada/purchase.parquet
Successfully loaded "purchase.parquet" into "Purchase" table
```

**Comment by epinzur** [comment]
good to hear.  I'm going to close this issue for now, but please create a new one if you encounter any other problems.
