### ISSUE TITLE
bug: Kaskada CLI "Listing" String Rendering

### ISSUE THREAD

**Issue by kevinjnguyen** [kaskada-ai/kaskada#336]
**Description**
In the Kaskada CLI hello world getting start [documentation](https://kaskada.io/docs-site/kaskada/main/getting-started/hello-world-cli.html), there are random "Listing" strings throughout the docs that do not help the usage of the documentation. 

**To Reproduce**
1. Navigate to: https://kaskada.io/docs-site/kaskada/main/getting-started/hello-world-cli.html#querying-data
2. See the Listing string on every fenlmagic block

**Actual Behavior**
There's an arbitrary Listing and number prefix on the fenl blocks.

**Expected Behavior**
No Listing/number string.

**Additional context**
N/A

**Relevant Logs / Links**
<img width="452" alt="Screenshot 2023-05-08 at 1 48 10 PM" src="https://user-images.githubusercontent.com/15032894/236907033-c2f3d55d-e13b-4df8-94cb-8f82e335f2e5.png">

**Comment by epinzur** [comment]
Note that this issue appears on multiple pages and not just the CLI getting started.
