### ISSUE TITLE
(ci) building antora docs as part of the PR fails when PR comes from a fork

### ISSUE THREAD

**Issue by therapon** [kaskada-ai/kaskada#397]
Currently the CI calls out to the docs/site repo to build the antora docs and verify that changes to documentation are valid. 

Unfortunately the call out to the docs/site repo requires a token to be passes. GitHub uses secrets from the PRs context and in a PR that was created from a fork the context is the forked repo. This means the token is missing which fails action. 

It would probably be easier to change the CI action so that we build the antora docs under this repo rather than calling out to an action on docs/site repo. 

1. Check out the code from docs/site here 
2. alter the playbook file to point to the PRs changes 
3. build antora in the action on this repo

**Comment by bjchambers** [comment]
Have we explored triggering the PR on [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) instead? If I read the docs right, this would run in this repo.

On the other hand, I'm sure there are security concerns there we should consider.
