### ISSUE TITLE
bug: Google Colab support is broken

### ISSUE THREAD

**Issue by epinzur** [kaskada-ai/kaskada#538]
**Description**
When trying to run Kaskada in Google Colab, it no longer works.  

**To Reproduce**
when I try to do this:
```
from kaskada.api.session import LocalBuilder
from kaskada import table as table

ksession = LocalBuilder().build()
```

I get:
```
ConnectionError: Unable to connect after 10 attempts
```

**Actual Behavior**
Local Session isn't starting

**Expected Behavior**
Local Session starts without issue.

**Additional context**
Error found on python clients: `v0.5.1`, `v0.5.0`, `v0.4.1`.   I didn't try older versions than this.  Engine/Manager were `v0.9.0`.

Also tried running on local jupyter notebook. This worked without issue on my Mac.

**Relevant Logs / Links**
Relevant stack traces, results, links, or screenshots of the issue.

From logs, it seems that the engine (sparrow) can't start due to a libssl issue: 
```
/root/.cache/kaskada/bin/engine@v0.9.0/kaskada-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by epinzur** [comment]
I was able to get kaskada working in colab by first installing libssl1.1:

```
!wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
!sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

Make sure to do the above before starting your Kaskada LocalSession.

**Comment by epinzur** [comment]
We've found that even after doing the above fix, Kaskada keeps having issues occasionaly.

```
IPython.core.error.UsageError: An exception occurred: Kaskada services are not available. If this is a local session, please restart the session.
```

Re-running the session cell fixes the issue for a while.

**Comment by therapon** [comment]
With regards to the libssl issue, it appears that Collab has upgraded the Ubuntu version running on their instances from 20.04 to 22.04
This upgrade to Ubuntu also upgrades the ssl library  from 1.1.1 to 3.0.9.
The Kaskada binary (through a dependency) depends on libssl. Our release builds are on Ubuntu 20.04. So when our kaskada binary is executed on a Ubuntu 22.04 it cannot find the appropriate version of libssl and fails to start the sparrow process.
