### ISSUE TITLE
feat: support struct as a `key` constraint

### ISSUE THREAD

**Issue by jordanrfrazier** [kaskada-ai/kaskada#552]
Support struct as a `key` constraint, which would allow us to use `struct` in lookups, with_key, etc.

**Comment by jordanrfrazier** [comment]
Fixed with https://github.com/kaskada-ai/kaskada/pull/545

**Comment by bjchambers** [comment]
Should we repurpose this ticket (or create one) for creating a test that `with_key` and `lookup` work with structs?
