### ISSUE TITLE
Final results, results at-time, results since-time

### ISSUE THREAD

**Issue by bjchambers** [kaskada-ai/kaskada#719]
- [x] preview/run "at" time
- [x] preview/run "since" time
- [x] final results
- [ ] update "time centric" notebook to demonstrate

**Comment by bjchambers** [comment]
@kerinin Thoughts on how we want to explain these? It seems weird to try to say: `run(history_or_snapshot, changed_since)` and then try to document that `changed_since` means "only points after this" for `history` and "only entities that changed after this" for `snapshot`.

We've talked about having separate run methods for "single query" and "materialize", but actually looking at the options, it seems like history vs. snapshot affects the available options and their meaning even more significantly. I wonder if we'd want to make *that* the top level thing:

```
timestream.all_points()
vs.
timestream.latest_points()
```

Alternatively, we could do this as separate classes for configuring the execution. The nice thing about that is we could potentially put the configuration in a variable and execute multiple timestreams with the same configuration. This also potentially clarifies the "when you execute you consume the iterator".

```
History(options...).to_pandas(timestream)
Snapshot(options...).to_pandas(timestream)
```

**Comment by jordanrfrazier** [comment]
I'm in favor of the suggestion, or a variation of this: 
```
timestream.all_points()
vs.
timestream.latest_points()
```

I think it comes back to the way of thinking -- as I experiment and write my query, I want to focus on the data first, what I want the query to do, _then_ on what I want the shape of the output to be. Similar to how one may want to define a query, then reuse it in various places with different filters on them.

**Comment by bjchambers** [comment]
@jordanrfrazier one option that I'm starting to like is:

1. Making one or more data classes to describe the different executions.
2. Having `run` take a few parameters.

For instance:

```
timestream.run(kd.destinations.Pulsar(...), History(...))
timestream.run(kd.destinations.Kafka(...), Snapshot(...))
```

Then the configuration can be managed by the `History` and `Snapshot` data classes. This also enables:

```
config = History(...)
timestream1.run(kd.destinations.Pulsar(...), config)
timestream2.run(kd.destinations.Kafka(...), config)
```

to compute two different timestreams to different locations using the same configuration.

The only thing that isn't a great fit to that is the destinations that produce an iterator or something like that.

**Comment by jordanrfrazier** [comment]
Yeah, I think that's a good thought. Let me sleep on it and do some reading and we can discuss tomorrow

**Comment by jordanrfrazier** [comment]
Although I do see the other side -- if I'm running multiple queries all to the same destination I don't want to have to specify that when I `run`. You could do
```
destination = kd.destinations.Pulsar(...)

ts1.run(destination)
```

but maybe a way to configure a default destination in the session: ```session.config(destination=kd.destinations.Pulsar(..)```

**Comment by bjchambers** [comment]
The problem with a default destination in the session is that if it uses the same topic, you quickly run into cases like two queries producing different schemas can't use the same topic. I think you'd be better off either passing that to `run`, or making it part of the `config` instance passed to `run`.

**Comment by bjchambers** [comment]
I think the case of pandas and direct outputs could be handled in a few ways:

1. Some kind of generic on the destination: `def run[T](destination: kd.Destination[T], config: RunConfig) -> T`. This would let us say `run(kd.dest.Pandas())` and get back a dataframe, `run(kd.dest.PandasIter())` and get back an iterator over dataframes, etc. We could default to `kd.dest.Pandas()` at which point `run()` and `preview()` are nearly equivalent.
2. Use the fact that config is a dataclass and we can easily pass it to multiple methods. `timestream.write(kd.dest.Pulsar(...), config)` to write to a destination, or `timestream.run_to_pandas(config)` to write to pandas, etc. (so we could have a few top level methods, but the "external" destinations all go through `write`.
